### ISSUE TITLE
Thanks for this was good to learn with.

### ISSUE THREAD

**Issue by rluiten** [vkammerer/react-redux-firebase#2]
Are you interested in any of the following branches ?
They are built on top of the previous one in order listed.

I have a branch for firebase 3.2.0
Another with hot loader 3.0.0 beta 2.
Another with some further refactoring i was toying with.

**Comment by vkammerer** [comment]
Hey @rluiten thank you for the work you've done!

I went through your branches and I see a lot of interesting things. Would it be possible for you to create different PRs for each separate feature, so that we can comment / accept them independently?

The most important to me seems to be the upgrade to the latest version of the firebase package. I haven't kept up to date with the new version of this package but what you've done seems great. Could you create a PR just for this one?

Regarding the upgrade of other packages and the overall architecture, I see you've done different things.
- I'm not sure that switching to webpack-dev-server is the best option. I like the fact that users own their server configuration, because it makes it very easy to implement additional server features. Moreover, the fact that setting up an express with webpack is extremely simple really reduces the benefit of webpack-dev-server. That can still be discussed in a separate issue though :)
- Users should understand what each package does, so I would really like to limit the number of dependencies we have in this repo. I see you've added extract-text-webpack-plugin, is it for CSS? this boilerplate should be completely agnostic in terms of CSS configuration and actually include no CSS at all. The same applies to html-webpack-plugin. Even if this might be a great and useful package, it doesn't belong to this simple boilerplate in my opinion.
- I see you've added babel-preset-stage-0 . Do you use any features of stage-0 itself? if possible, I would like to use the highest stage necessary for our codebase. One of the key features I would like to add in the near future is to replace redux-thunk with redux-saga, which requires generator functions support, which is already available in stage-2.

And good work on the refactoring, that looks good to me :) I'd be glad to accept a PR there too.

**Comment by rluiten** [comment]
I like webpack-dev-server I don't like having to have to muck with my own local server.
Most of the time I need to deal with other back ends so a node based server is of little to no value to me.
I also would not deploy in production a webpack generated solution I'd use a generated build.

Also webpack-dev-server is one of the some what outlined paths to get hot module replacement v3 beta going which is what I really wanted to try out.

The main reason I have html-webpack-plugin is so that in either production or development mode it uses the same source html file with no stuffing around. I could not get this to happen with out lots of extra mucking about otherwise. Being able to flip back and forth between development and production I've always found very useful in most projects.

I quite like redux-thunk though being able to do pretty much anything might not be good for me some times as it increase the chance I may do something that is not as as maintainable in the long run.

I have been using redux-promise-middleware in another project and generally find it good though it is quite narrow in what it does I find it covers most bases well, one of its big wins is that it is very simple in concept. I did a bunch of reading and think redux-loop is more interesting than redux-saga at the moment and discussed with a friend who went from loop to saga and ended up going back to loop.

I checked and stage-0 is not required I was having a problem with something and it got left in for no good reason.
I need only stage-2 to use object rest spread which I find really useful and really miss when I am in typescript at the moment.
I see that async generator support is now in babel stage-3 as well.

**Comment by rluiten** [comment]
I have a new branch alternate-refactoring that does the refactoring based on the firebase 3.2.0 update branch (rather than the one I have with webpack-dev-server and hot module reloading and other packages). I don't think I can easily create a pull request for till you decide to merge the previous branch, so I'll wait for your feedback.

**Comment by vkammerer** [comment]
Upgrade to firebase 3.2.0 done with https://github.com/vkammerer/react-redux-firebase/pull/3

**Comment by vkammerer** [comment]
Thank you @rluiten for the upgrade to Firebase 3.2.0

Moving forward, I agree that we can replace the current express server with webpack-dev-server. My argument of owning a server config is not relevant in this case as the point of Firebase is precisely to be a no-backend technology.
Do you want to make a PR for the move to webpack-dev-server too?

Regarding the other issues we talked about, let's keep it simple for now. So we can leave redux-thunk as it is for now and keep to conversation between redux-loop and redux-saga for another thread.
As I said I don't want to add too many dependencies and users should understand what is going on in the repo without having to investigate additional packages. So we can leave out html-webpack-plugin or extract-text-webpack-plugin.

**Comment by vkammerer** [comment]
I am going to edit the README to add an intention to integrate webpack-dev-server, and close this issue. Thanks again!

**Comment by vkammerer** [comment]
I just updated the repo with webpack2, and we are now using webpack dev server.

**Comment by rluiten** [comment]
Sounds good, I have yet to try out webpack2, other stuff keeps pushing it back for me lately.
